//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayHistory
    {
        public int PayHistoryId { get; set; }
        public int PaymentId { get; set; }
        public decimal Amount { get; set; }
        public string PaidBy_UserId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
